### ISSUE TITLE
Command "gauge init ts" returns 404

### ISSUE THREAD

**Issue by uniconstructor** [getgauge/template-ts#12]
Log output:
```sh
gauge init ts
Initializing template from https://github.com/getgauge/template-ts/releases/latest/download/ts.zip
Error ----------------------------------

[Gauge]
Failed to initialize project. Error downloading file: https://github.com/getgauge/template-ts/releases/latest/download/ts.zip.
404 Not Found. Please use a valid Gauge template URI or check network connection

Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://github.com/getgauge/gauge/discussions

Your Environment Information -----------
        linux, 1.5.1, bdc0f73
        js (2.4.0), ts (0.1.0)
```

**Comment by Ionicson** [comment]
Hi, I encountered the same problem as you. My observation is that something went wrong during the build and file ts.zip is missing in latest template version. I manually downloaded ts.zip from the previous version (0.0.8) and initialised the project from the .zip file. As I see now you can provide URL address of template .zip file so you can skip file download and point gauge to the correct .zip file from the previous release.

**Comment by BugDiver** [comment]
@Ionicson @uniconstructor The release has been fixed and `gauge init ts` should work now.
